# Generated by Django 6.0.2 on 2026-03-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('uid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('photos_url', models.CharField(max_length=32)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
