# Generated by Django 6.0.2 on 2026-03-02 21:39

import admin_dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizeduser',
            name='photos_url',
        ),
        migrations.CreateModel(
            name='AuthorizedUserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=admin_dashboard.models.user_photo_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='admin_dashboard.authorizeduser')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
