# Generated by Django 6.0.2 on 2026-04-20 09:56

import admin_dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_remove_authorizeduser_photos_url_authorizeduserphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizeduserphoto',
            name='photo',
            field=models.ImageField(upload_to=admin_dashboard.models.user_photo_path, validators=[admin_dashboard.models.validate_image_type]),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uid_hash', models.CharField(max_length=64)),
                ('result', models.CharField(choices=[('GRANTED', 'Prístup povolený'), ('DENIED_BLOCKED', 'Zamietnutý - zablokovaný'), ('DENIED_UNKNOWN', 'Zamietnutý - neznáma karta'), ('DENIED_FACE', 'Zamietnutý - tvár nerozpoznaná')], max_length=20)),
                ('device', models.CharField(default='Unknown device', max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='admin_dashboard.authorizeduser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
